### PR TITLE
Fix neofetch logo not showing and make wallpaper easier to set

### PR DESCRIPTION
**Pull request by mycpphurts**
Found your dotfiles from r/unixporn (Great work on these btw) and decided to try them out, upon testing, I found out that the wallpaper didn't display (because I didn't change the location in my sway config lol) and that the logo in neofetch didn't show either.

I found the issue rather quickly, as shown below.
https://github.com/laggy-tux/sway-Dots/blob/dc7f0f6886da897fd7bd1ede167f320a0a58b5bd/config/neofetch/config.conf#L743

Upon further reading your code, I decided to make some changes for people who just CTRL + C and CTRL + V the dotfiles.

Changes include:
- Making the neofetch logo visible by changing the home path from ```/home/lagg/``` to ```$HOME```
- Moving the wallpaper into a folder named ```walls``` that can be dragged into the home directory
- Updating the README.md to tell the user cloning to move ```walls``` into their Home directory.

### CODE REVIEW

**Comment by laggy-tux** [comment]
@mycpphurts  the path for the neofetch maybe different for you.. please change that...(around line 743 in the config file) and for the wallpapers i added it to the ```themes``` config file over at the sway folder(retstart ur device for the change to occuer,mod+shift+c did not change it for me).... i think this should give u an idea

**Comment by mycpphurts** [comment]
For neofetch you don't have to Mod+Shift+C

The change I did to the neofetch config file was make it so it uses the global Home directory (aka `$HOME`) instead of a fixed user (in your case ```/home/lagg/```) that way, the custom logo for neofetch gets displayed regardless of username.

As for the wallpaper, making it into a folder named wall that has to be moved into the home directory, just respects the provided location for the wallpaper on the sway files, making it easier for new people to sway and linux to set the wallpaper.

**Comment by laggy-tux** [comment]
> For neofetch you don't have to Mod+Shift+C
> 
> The change I did to the neofetch config file was make it so it uses the global Home directory (aka `$HOME`) instead of a fixed user (in your case `/home/lagg/`) that way, the custom logo for neofetch gets displayed regardless of username.
> 
> As for the wallpaper, making it into a folder named wall that has to be moved into the home directory, just respects the provided location for the wallpaper on the sway files, making it easier for new people to sway and linux to set the wallpaper.

okay now that makes sense.... ill make that change in my repo aswell

**Comment by mycpphurts** [comment]
You could've accepted the PR. But the changes you made to it kinda made it conflict. You can use this as a base, or if you want, I can discard my commits, sync with main and re-add my changes 😄

**Comment by mycpphurts** [comment]
Judging by the commit history, I'll be closing the PR. Thanks for taking a look into it though!

**Pull request closed without merging**
